timeline_buttons_enabled:
  default: true
  client: true

mobile_buttons_enabled:
  default: true
  client: true

edit_button_enabled:
  default: true
  client: true

edit_button_label:
  default: "Jump"
  client: true
  
edit_button_title:
  default: "Edit this Topic"
  client: true
  
